### ISSUE TITLE
HighFreq Installation on Windows (R-4.2.1 / Rtools42 / RStudio)

### ISSUE THREAD

**Issue by cpanagakos** [algoquant/HighFreq#5] opened 2022-07-21 13:49 UTC
Firstly, I appreciate all the hard work and thought that went into creating this HighFreq package.  The package is intriguing, but I have had significant trouble getting it to install on my Windows machine.  I am posting as I may not be the only one encountering these difficulties, and hope the post will generate useful guidance that will benefit many.

As referenced in the subject, I am trying to install on Windows machine using R-4.2.1 / Rtools42 / RStudio.  Rtools42 is installed at C:\rtools42.

Per the Vignette, I successfully ran ``` install.packages("remotes") ```, but problem occurs during install via ``` remotes::install_github("algoquant/HighFreq") ```.

Per README, I also ran via ``` install.packages("devtools") ```, but install again similarly failed via ```  devtools::install_github(repo="algoquant/HighFreq") ```.

The errors point to **"undefined reference to [various files]"**, like `ddot_', `dsyev_', `dgesvd_', etc., as illustrated via the final error text copied below:

> C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: HighFreq.o:HighFreq.cpp:(.text$_ZN4arma6auxlib8svd_econIdEEbRNS_3MatIT_EERNS_3ColIS3_EES5_S5_c[_ZN4arma6auxlib8svd_econIdEEbRNS_3MatIT_EERNS_3ColIS3_EES5_S5_c]+0x431): undefined reference to `dgesvd_'

> collect2.exe: error: ld returned 1 exit status
> no DLL was created
> ERROR: compilation failed for package 'HighFreq'
> * removing 'C:/Program Files/R/R-4.2.1/library/HighFreq'

For what it's worth (I am not a computer science guy), I also ran the below as a result of my independent search for a solution, but have done nothing to change or "set" any particular path or environment:

``` Sys.getenv("HOME")```

> [1] "C:/Users/Administrator/Documents"

``` Sys.getenv("PATH")```
> [1] "C:\\Rtools\\bin;C:\\rtools42\\x86_64-w64-mingw32.static.posix\\bin;C:\\rtools42\\usr\\bin;C:\\Program Files\\R\\R-4.2.1\\bin\\x64;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files (x86)\\Common Files\\Intuit\\QBPOSSDKRuntime;C:\\Program Files (x86)\\ExchangeMapi;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files\\RStudio\\bin\\quarto\\bin"

Any guidance is greatly appreciated.  Thank you.

**Comment by algoquant** [comment] 2022-07-21 19:09
I managed to reproduce the error on a Windows machine (I usually use a Mac).
I believe the errors are caused by link errors with LAPACK or BLAS.  This didn't happen before on Windows, so I'm puzzled. 
The fix may require customizing the makefile.  I'll post once I find a solution.

**Comment by cpanagakos** [comment] 2022-07-21 21:06
Hi Jerzy - yes, I saw some related posts about BLAS and LAPACK on Stackoverflow while searching for a solution, but no obvious / ez answers, at least from my end.

I really appreciate all that you have and continue to do for the community.  Look forward to working with the HighFreq package after you post a solution.

All the best to you and yours...Christian

________________________________

**Comment by algoquant** [comment] 2022-09-08 15:12
@cpanagakos 
I fixed the package build errors.
I confirmed that the C++ source code compiles fine using Rcpp::sourceCpp().  So it was a link error due to a corrupt configuration setting.  I couldn't identify what it was - it installed fine under Windows until a few months ago.
So I created a new RcppArmadillo package and moved the R and C++ source code there.  Then I replaced the whole HighFreq directory with the new package.
I confirmed that it can be installed under both Windows and Mac using:
devtools::install_github("algoquant/HighFreq")
Please confirm and I will close this issue.

**Comment by cpanagakos** [comment] 2022-09-14 08:42
@algoquant 
Success!  The package installed and loaded.  I look forward to learning more about it and using it.
Thank you again for your response, and all that you do.

**Closed** 2022-09-14 20:42 UTC
